#ifndef ISR80H_H
#define ISR80H_H

enum SystemCommands
{
    SYSTEM_COMMAND0_EXIT,
    SYSTEM_COMMAND1_PRINT,
    SYSTEM_COMMAND2_GETKEY,
    SYSTEM_COMMAND3_PUTCHAR,
    SYSTEM_COMMAND4_MALLOC,
    SYSTEM_COMMAND5_FREE,
    SYSTEM_COMMAND6_PROCESS_LOAD_START,
    SYSTEM_COMMAND7_INVOKE_SYSTEM_COMMAND,
    SYSTEM_COMMAND8_GET_PROGRAM_ARGUMENTS,
    SYSTEM_COMMAND9_CLRSCR,
    SYSTEM_COMMAND10_FOPEN,
    SYSTEM_COMMAND11_FCLOSE,
    SYSTEM_COMMAND12_FREAD,
    SYSTEM_COMMAND13_FWRITE,
    SYSTEM_COMMAND14_REMOTE_TEMINATE,
    SYSTEM_COMMAND15_PROCSS_INF,
    SYSTEM_COMMAND16_NEW_THREAD,
    SYSTEM_COMMAND17_CREATE_SHARED_MEMORY,
    SYSTEM_COMMAND18_WRITE_SECTOR,
    SYSTEM_COMMAND19_READ_SECTOR,
    SYSTEM_COMMAND20_FSTAT,
    SYSTEM_COMMAND21_FTELL,
    SYSTEM_COMMAND22_FSEEK,
    SYSTEM_COMMAND23_REMOVE,
    SYSTEM_COMMAND24_SET_CURSOR,
    SYSTEM_COMMAND25_DRAW_BLOCK,
    SYSTEM_COMMAND26_PLAY_SOUND,
    SYSTEM_COMMAND27_QUIT_SOUND,
    SYSTEM_COMMAND28_FORK
};

void isr80h_register_commands();

#endif