#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10


#define SERPAEOS_TOTAL_INTERRUPTS 512

#define SERPAEOS_HEAP_SIZE_BYTES (104857600 * 16)
#define SERPAEOS_HEAP_BLOCK_SIZE 4096
#define SERPAEOS_HEAP_ADDRESS 0x01000000 
#define SERPAEOS_HEAP_TABLE_ADDRESS 0x1000

#define SERPAEOS_DEFAULT_SECTOR_SIZE 512
#define CD_SECTOR_SIZE 2048

#define SERPAEOS_MAX_FILESYSTEMS 12
#define SERPAEOS_MAX_FILE_DESCRIPTORS 512
#define SERPAEOS_MAX_DIRECTORY_DESCRIPTORS 512

#define SERPAEOS_MAX_PATH 108

#define SERPAEOS_TOTAL_GDT_SEGMENTS 6

#define SERPAEOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define SERPAEOS_USER_PROGRAM_STACK_SIZE (1024 * 16)
#define SERPAEOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define SERPAEOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END (SERPAEOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - SERPAEOS_USER_PROGRAM_STACK_SIZE)

#define SERPAEOS_MAX_PROGRAM_ALLOCATIONS 1024

//max MAIN processes
#define SERPAEOS_MAX_PROCESSES 13
//max total processes (both main processes and fork())
#define SERPAEOS_TOTAL_MAX_PROCESSES 50

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b

#define SERPAEOS_MAX_ISR80H_COMMANDS 1024

#define SERPAEOS_KEYBOARD_BUFFER_SIZE 1024

//primary master (boot disk, unpartitioned); three more disks, each may be partitioned with 4 partitions
#define SERPAEOS_MAX_DISKS 13

#define EOF (-1)

#endif